[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dbwarden"
version = "0.1.2"
description = "Database migration system for Python/SQLAlchemy projects"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
    { name = "Emiliano Gandini Outeda", email = "emiliano.gandini@protonmail.com" }
]
keywords = [
    "database",
    "migrations",
    "sqlalchemy",
    "fastapi",
    "postgres",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "aiosqlite>=0.22.1",
    "asyncpg>=0.29.0,<0.32.0",
    "packaging>=25.0",
    "rich>=12.2.0",
    "sqlalchemy>=2.0.10",
    "typer>=0.12.3",
]

[project.scripts]
dbwarden = "dbwarden.cli.main:main"

[project.optional-dependencies]
dev = [
    "psycopg2-binary>=2.9.11",
    "pytest>=8.4.2",
    "pytest-asyncio>=0.24.0",
]
postgres-async = [
    "asyncpg>=0.29.0,<0.32.0",
    "sqlalchemy[postgresql]>=2.0.10",
]
postgres-sync = [
    "psycopg2-binary>=2.9.11",
]
sqlite-async = [
    "aiosqlite>=0.22.1",
]

[tool.hatch.build.targets.wheel]
packages = ["dbwarden"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
